---
- shell: creates=/etc/pki/tls/certs/rsyslog.csr openssl req -newkey rsa:2048 -nodes 
   -keyout /etc/pki/tls/private/rsyslog.key 
   -out /etc/pki/tls/certs/rsyslog.csr 
   -subj "/CN=rsyslog.lab.local"
- shell: openssl x509 -req -sha256 -days 3652
   -in /etc/pki/tls/certs/rsyslog.csr 
   -out /etc/pki/tls/certs/rsyslog.crt
   -CA /etc/pki/tls/certs/localsrvca.crt 
   -CAkey /etc/pki/tls/private/localsrvca.key 
   -CAcreateserial 

- yum: name=rsyslog-gnutls state=installed

- yum: name=policycoreutils-python state=installed
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 7
- yum: name=policycoreutils-python-utils state=installed
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8
- shell: semanage port -a -t syslogd_port_t -p tcp {{ syslog_tcp_port }}
  ignore_errors: yes

- template: src=sslserver.j2 dest=/etc/rsyslog.d/sslserver.conf owner=root group=root mode=0600

- service: name=rsyslog state=restarted
