#!/bin/bash

# apache 
curl -L http://crt1.lab.home
curl -L http://crt2.lab.home
curl https://crt1.lab.home
curl https://crt2.lab.home

# haproxy
curl https://www.lab.home:1443

# tomcat
curl https://tomcat.lab.home:8443

# vsftp
curl --ftp-ssl --use-ascii --user vagrant:vagrant --list-only ftp://ftp.lab.home/

# nginx
curl -L http://crt1.lab.home:2080
curl -L http://crt2.lab.home:2080
curl https://crt1.lab.home:2443
curl https://crt2.lab.home:2443
