#!/bin/bash

# apache 
curl -L http://crt1.lab.local
curl -L http://crt2.lab.local
curl https://crt1.lab.local
curl https://crt2.lab.local

# haproxy
curl https://www.lab.local:1443

# tomcat
curl https://tomcat.lab.local:8443

# vsftp
curl --ftp-ssl --use-ascii --user vagrant:vagrant --list-only ftp://ftp.lab.local/

# nginx
curl -L http://crt1.lab.local:2080
curl -L http://crt2.lab.local:2080
curl https://crt1.lab.local:2443
curl https://crt2.lab.local:2443
