#!/bin/bash

BASE=`dirname $0`
CADB=${BASE}/files/cacerts
  
if [ ! -d ${CADB}/ ]
then
  mkdir -p ${CADB}/
fi

if [ ! -f ${CADB}/homeroot.idx ]
then
  touch ${CADB}/homeroot.idx
  echo "unique_subject = no" > ${CADB}/homeroot.idx.attr
fi

if [ ! -f ${CADB}/homeroot.srl ]
then
  openssl rand -hex -out ${CADB}/homeroot.srl 20
fi

openssl req -newkey rsa:2048 -nodes \
-keyout ${CADB}/homeroot.key \
-out ${CADB}/homeroot.csr \
-subj "/C=AU/O=Home Lab/OU=www.lab.home/CN=Home Lab Root"

openssl ca -batch -selfsign -startdate 20200101010000Z -enddate 20491231122359Z \
-in ${CADB}/homeroot.csr \
-out ${CADB}/homeroot.crt \
-keyfile ${CADB}/homeroot.key \
-name root_CA \
-config <(cat \
<(printf "[ root_CA ]\n") \
<(printf "database=${CADB}/homeroot.idx\n") \
<(printf "unique_subject=no\n") \
<(printf "default_md=sha256\n") \
<(printf "email_in_dn=no\n") \
<(printf "rand_serial=yes\n") \
<(printf "default_days=365\n") \
<(printf "serial=${CADB}/homeroot.srl\n") \
<(printf "new_certs_dir=${CADB}/\n") \
<(printf "policy=policy_anything\n") \
<(printf "[ policy_anything ]\n") \
<(printf "countryName=optional\n") \
<(printf "stateOrProvinceName=optional\n") \
<(printf "localityName=optional\n") \
<(printf "organizationName=optional\n") \
<(printf "organizationalUnitName=optional\n") \
<(printf "commonName=supplied\n") \
<(printf "emailAddress=optional\n") \
) \
-extensions exts \
-extfile <(cat \
<(printf "[ exts ]\n") \
<(printf "basicConstraints=critical,CA:true\n") \
<(printf "keyUsage=critical,digitalSignature,keyCertSign,cRLSign\n") \
<(printf "extendedKeyUsage=serverAuth,clientAuth\n") \
<(printf "subjectKeyIdentifier=hash\n") \
<(printf "authorityKeyIdentifier=keyid:always,issuer\n") \
)

openssl verify -CAfile ${CADB}/homeroot.crt ${CADB}/homeroot.crt


if [ ! -f ${CADB}/homeclnca.idx ]
then
  touch ${CADB}/homeclnca.idx
  echo "unique_subject = no" > ${CADB}/homeclnca.idx.attr
fi

if [ ! -f ${CADB}/homeclnca.srl ]
then
  openssl rand -hex -out ${CADB}/homeclnca.srl 20
fi

openssl req -newkey rsa:2048 -nodes \
-keyout ${CADB}/homeclnca.key \
-out ${CADB}/homeclnca.csr \
-subj "/C=AU/O=Home Lab/OU=www.lab.home/CN=Home Lab Clients CA"

openssl ca -batch -startdate 20200101010000Z -enddate 20491231122359Z \
-in ${CADB}/homeclnca.csr \
-out ${CADB}/homeclnca.crt \
-keyfile ${CADB}/homeroot.key \
-cert ${CADB}/homeroot.crt \
-name root_CA \
-config <(cat \
<(printf "[ root_CA ]\n") \
<(printf "database=${CADB}/homeroot.idx\n") \
<(printf "unique_subject=no\n") \
<(printf "default_md=sha256\n") \
<(printf "email_in_dn=no\n") \
<(printf "rand_serial=yes\n") \
<(printf "default_days=365\n") \
<(printf "serial=${CADB}/homeroot.srl\n") \
<(printf "new_certs_dir=${CADB}/\n") \
<(printf "policy=policy_anything\n") \
<(printf "[ policy_anything ]\n") \
<(printf "countryName=optional\n") \
<(printf "stateOrProvinceName=optional\n") \
<(printf "localityName=optional\n") \
<(printf "organizationName=optional\n") \
<(printf "organizationalUnitName=optional\n") \
<(printf "commonName=supplied\n") \
<(printf "emailAddress=optional\n") \
) \
-extensions exts \
-extfile <(cat \
<(printf "[ exts ]\n") \
<(printf "basicConstraints=critical,CA:true,pathlen:0\n") \
<(printf "keyUsage=critical,digitalSignature,keyCertSign,cRLSign\n") \
<(printf "extendedKeyUsage=serverAuth,clientAuth\n") \
<(printf "subjectKeyIdentifier=hash\n") \
<(printf "authorityKeyIdentifier=keyid:always,issuer\n") \
)

openssl verify -CAfile ${CADB}/homeroot.crt ${CADB}/homeclnca.crt

if [ ! -f ${CADB}/homesrvca.idx ]
then
  touch ${CADB}/homesrvca.idx
  echo "unique_subject = no" > ${CADB}/homesrvca.idx.attr
fi

if [ ! -f ${CADB}/homesrvca.srl ]
then
  openssl rand -hex -out ${CADB}/homesrvca.srl 20
fi

openssl req -newkey rsa:2048 -nodes \
-keyout ${CADB}/homesrvca.key \
-out ${CADB}/homesrvca.csr \
-subj "/C=AU/O=Home Lab/OU=www.lab.home/CN=Home Lab Server CA"

openssl ca -batch -days 7304 \
-in ${CADB}/homesrvca.csr \
-out ${CADB}/homesrvca.crt \
-keyfile ${CADB}/homeroot.key \
-cert ${CADB}/homeroot.crt \
-name root_CA \
-config <(cat \
<(printf "[ root_CA ]\n") \
<(printf "database=${CADB}/homeroot.idx\n") \
<(printf "unique_subject=no\n") \
<(printf "default_md=sha256\n") \
<(printf "email_in_dn=no\n") \
<(printf "rand_serial=yes\n") \
<(printf "default_days=365\n") \
<(printf "serial=${CADB}/homeroot.srl\n") \
<(printf "new_certs_dir=${CADB}/\n") \
<(printf "policy=policy_anything\n") \
<(printf "[ policy_anything ]\n") \
<(printf "countryName=optional\n") \
<(printf "stateOrProvinceName=optional\n") \
<(printf "localityName=optional\n") \
<(printf "organizationName=optional\n") \
<(printf "organizationalUnitName=optional\n") \
<(printf "commonName=supplied\n") \
<(printf "emailAddress=optional\n") \
) \
-extensions exts \
-extfile <(cat \
<(printf "[ exts ]\n") \
<(printf "basicConstraints=critical,CA:true,pathlen:0\n") \
<(printf "keyUsage=critical,digitalSignature,keyCertSign,cRLSign\n") \
<(printf "extendedKeyUsage=serverAuth,clientAuth\n") \
<(printf "subjectKeyIdentifier=hash\n") \
<(printf "authorityKeyIdentifier=keyid:always,issuer\n") \
)

openssl verify -CAfile ${CADB}/homeroot.crt ${CADB}/homesrvca.crt
