#!/bin/bash

BASE=`dirname $0`
CADB=${BASE}/files/cacerts

if [ ! -d ${CADB}/ ]
then
  mkdir -p ${CADB}/
fi

if [ ! -f ${CADB}/homeroot.srl ]
then
  openssl rand -hex -out ${CADB}/homeroot.srl 20
fi

openssl req -new -newkey rsa:2048 -x509 -nodes -sha256 -days 7304 \
-keyout ${CADB}/homeroot.key \
-out ${CADB}/homeroot.crt \
-subj "/C=AU/O=Home Lab/OU=www.lab.home/CN=Home Lab Root" \
-extensions exts \
-config <(cat \
<(printf "[ req ]\n") \
<(printf "distinguished_name=req_distinguished_name\n") \
<(printf "[ req_distinguished_name ]\n") \
<(printf "[ exts ]\n") \
<(printf "keyUsage=critical,digitalSignature,keyCertSign,cRLSign\n") \
<(printf "basicConstraints=critical,CA:true\n") \
<(printf "subjectKeyIdentifier=hash\n") \
<(printf "authorityKeyIdentifier=keyid\n") \
)

openssl verify -CAfile ${CADB}/homeroot.crt ${CADB}/homeroot.crt


openssl req -newkey rsa:2048 -nodes \
-keyout ${CADB}/homeclnca.key \
-out ${CADB}/homeclnca.csr \
-subj "/C=AU/O=Home Lab/OU=www.lab.home/CN=Home Lab Clients CA"

openssl x509 -req -days 7304 -sha256 \
-in ${CADB}/homeclnca.csr \
-out ${CADB}/homeclnca.crt \
-CA ${CADB}/homeroot.crt -CAkey ${CADB}/homeroot.key \
-CAcreateserial -CAserial ${CADB}/homeroot.srl \
-extensions exts \
-extfile <(cat \
<(printf "[ exts ]\n") \
<(printf "basicConstraints=critical,CA:true,pathlen:0\n") \
<(printf "keyUsage=critical,digitalSignature,keyCertSign,cRLSign\n") \
<(printf "extendedKeyUsage=serverAuth,clientAuth\n") \
<(printf "subjectKeyIdentifier=hash\n") \
<(printf "authorityKeyIdentifier=keyid:always,issuer\n") \
)

openssl verify -CAfile ${CADB}/homeroot.crt ${CADB}/homeclnca.crt


openssl req -newkey rsa:2048 -nodes \
-keyout ${CADB}/homesrvca.key \
-out ${CADB}/homesrvca.csr \
-subj "/C=AU/O=Home Lab/OU=www.lab.home/CN=Home Lab Server CA"

openssl x509 -req -days 7304 -sha256 \
-in ${CADB}/homesrvca.csr \
-out ${CADB}/homesrvca.crt \
-CA ${CADB}/homeroot.crt -CAkey ${CADB}/homeroot.key \
-CAcreateserial -CAserial ${CADB}/homeroot.srl \
-extensions exts \
-extfile <(cat \
<(printf "[ exts ]\n") \
<(printf "basicConstraints=critical,CA:true,pathlen:0\n") \
<(printf "keyUsage=critical,digitalSignature,keyCertSign,cRLSign\n") \
<(printf "extendedKeyUsage=serverAuth,clientAuth\n") \
<(printf "subjectKeyIdentifier=hash\n") \
<(printf "authorityKeyIdentifier=keyid:always,issuer\n") \
)

openssl verify -CAfile ${CADB}/homeroot.crt ${CADB}/homesrvca.crt
